[package]
name = "cashier-server"
version = "0.1.0"
authors = ["Sun Ziping <sunziping2016@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
bson = "0.14.1"
clap = "3.0.0-beta.1"
chrono = "0.4"
env_logger = "0.7.1"
err-derive = "0.2.4"
log = "0.4.8"
mongodb = "0.10.0"
serde = "1.0.111"
serde_json = "1.0"
shell-macro = { path = "../shell-macro" }
tokio = { version = "0.2.21", features = ["full"] }
