[package]
name = "cashier-server"
version = "0.1.0"
authors = ["Sun Ziping <sunziping2016@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
bcrypt = "0.8.0"
bson = "1.0"
clap = "3.0.0-beta.1"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.7.1"
err-derive = "0.2.4"
futures = "0.3.5"
jsonwebtoken = "7.1.1"
log = "0.4.8"
mongodb = "1.0"
rand = "0.7.3"
rpassword = "4.0.5"
serde = "1.0.111"
serde_json = "1.0"
shell-macro = { path = "../shell-macro" }
tokio = { version = "0.2.21", features = ["full"] }
